# Generated by Django 3.2.7 on 2021-10-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.OneToOneField(help_text='Select a price row for this product', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.pricerow'),
        ),
    ]
