# Generated by Django 3.2.7 on 2021-10-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_pricerow_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
