# Generated by Django 3.2.7 on 2021-10-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerow',
            name='group_value',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
